name: Render Deploy

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

jobs:
  #1 login docker, build image, push image
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login in to Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Image
        run: |
          docker build \
            -f Dockerfile.prod \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:${{github.sha}} .

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nestjs-app:${{github.sha}}

  #2 configs on AWS
  prepare-configs:
    name: copy configs & create .env
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: copy config files
        uses: appleboy/scp-action@v1
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          source: 'docker-compose.yml,nginx/*'
          target: '/home/ubuntu/app'
          stripe_components: 0

      - name: create env file
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script: |
            echo "MONGO_URI=${{secrets.MONGO_URI}}" > /home/ubuntu/app/.env
            echo "PORT=${{secrets.PORT}}" >> /home/ubuntu/app/.env

  #3 deploy
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: prepare-configs
    steps:
      - name: deploy through ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script: |
            cd '/home/ubuntu/app'
            sudo docker compose pull
            sudo docker compose up -d
            sudo docker image prune -af
